Rectangle/Snapping/SnappingManager.swift
Rectangle/WindowCalculation/AlmostMaximizeCalculation.swift
Rectangle/WindowCalculation/BottomHalfCalculation.swift
Rectangle/WindowCalculation/CenterCalculation.swift
Rectangle/WindowCalculation/CenterThirdCalculation.swift
Rectangle/WindowCalculation/ChangeSizeCalculation.swift
Rectangle/WindowCalculation/FirstThirdCalculation.swift
Rectangle/WindowCalculation/FirstTwoThirdsCalculation.swift
Rectangle/WindowCalculation/LastThirdCalculation.swift
Rectangle/WindowCalculation/LastTwoThirdsCalculation.swift
Rectangle/WindowCalculation/LeftRightHalfCalculation.swift
Rectangle/WindowCalculation/LowerLeftCalculation.swift
Rectangle/WindowCalculation/LowerRightCalculation.swift
Rectangle/WindowCalculation/MaximizeCalculation.swift
Rectangle/WindowCalculation/MaximizeHeightCalculation.swift
Rectangle/WindowCalculation/MoveDownCalculation.swift
Rectangle/WindowCalculation/MoveLeftRightCalculation.swift
Rectangle/WindowCalculation/MoveUpCalculation.swift
Rectangle/WindowCalculation/NextPrevDisplayCalculation.swift
Rectangle/WindowCalculation/TopHalfCalculation.swift
Rectangle/WindowCalculation/UpperLeftCalculation.swift
Rectangle/WindowCalculation/UpperRightCalculation.swift
Rectangle/WindowCalculation/WindowCalculation.swift
Rectangle/WindowManager.swift

…cking if a rect is centered within another rect
Fixes the issue of iTerm/Terminal windows not being resized down to a 1/3 & 2/3 due their own resize logic which rounds up/down to the height of a line

Terminal/iTerm 2 - Fix a resize bug regarding not resizing to a 2/3 & 1/3 (top & bottom) 

---

Rectangle/zh-Hans.lproj/Main.strings

Fix wrong machine translations.
Leave application name as untranslated name.
Use correct term commonly used by macOS, such as `Find` `Copy` `Cut` `Paste` `Smart` `Help` `Preferences` translations.
Add missing space between English and Chinese to improve readability.

Correct wrong zh-Hans translations manually

---

Rectangle/ShortcutManager.swift

Fixes rxhanson/Rectangle#69
`NSMenuItem.keyEquivalent` only displays the first character of the set string in the menu. To be able to display key equivalents like “F12”, we need to use font glyphs that render that entire character (which are defined by Apple in a private area of the unicode table: https://developer.apple.com/documentation/appkit/1535851-function-key_unicodes?language=objc)
MASShortcut already supports this with `MASSShortcut.keyCodeStringForKeyEquivalent`. We just need to return this property instead of the more human-readable `keyCodeString` when we want a string that can be used with `NSMenuItem.keyEquivalent`.

Display function keys correctly in status bar menu

---

Rectangle/zh-Hant.lproj/Main.strings

Corrected "First Third" from '左三之一' to '左三分之一'
Sorry for the typo and thanks to @networm for reminder!

Corrected a typo

---

Rectangle/ja.lproj/Main.strings

- Replaced machine translations by making references to comments in the strings file.
- Used half-width characters for numbers.
- Some wordings are left because they seem to be unused.

Improve japanese wordings

---

Rectangle/fr.lproj/Main.strings

"Fermer les fenêtres en les faisant glisser" means "Close windows by dragging" which is not what the feature does.
"Snap" is not easy to translate in French in this context, I translated it as "Redimensionner" which means "Resize", I hope that's ok.

FR translation fix for snap area option in settings

---

Rectangle/WindowCalculation/ChangeSizeCalculation.swift

Fixes the following type of scenario when using gapSize:
- move window to a corner
- make window smaller
- the window is now shrunk away from the corner (unlike the non-gapSize
behavior where the window stays "glued" to the edges)
(This also includes some minor consistency fixes.)
A detail I considered: changing sizes when a window is at an edge will
eliminate the gap between the window and the edge. I thought about
preserving the gap with the edge, but this behavior feels reasonable and
trying to preserve the gap would create a bunch of *ahem* edge cases to
deal with (eg if a window is full height, doing a increase-size command
shouldn't add gaps to avoid making the height smaller).

account for gapSize when changing window size

---

Rectangle/es.lproj/Main.strings

Lowecased words that do not need to be uppercase.
Corrected a translation with terms that sound more familiar in Spanish language.

Updated Spanish strings.

---

Rectangle/de.lproj/Main.strings

One thing I noticed when completing these translations was that `View Logs...` used three dots rather than an ellipsis (`…`) as used elsewhere in the app and in macOS. I have corrected this in my translation to German, but not anywhere else.

Translate new strings to German

---

Rectangle/WindowAction.swift
Rectangle/WindowCalculation/BottomCenterSixthCalculation.swift
Rectangle/WindowCalculation/BottomRightSixthCalculation.swift
Rectangle/WindowCalculation/TopCenterSixthCalculation.swift

A couple of bug fixes:
- Add a gap around centerHalf, for consistency with all other fractional positions.
- Correct orientation of Bottom Right Sixth on vertical displays.
- Update the repetition sequence on center sixths in portrait: previously the window would jump between the two sides of the screen, whereas now it will stay on the same side as it cycles through the center-sixth and the two two-sixths positions.
Before and after (center sixths commands):

Fix gap on center half and positioning of vertical sixths

---

Rectangle/AccessibilityElement.swift

This PR should fix the issue noted in the README regarding [windows not resizing to the proper dimensions](https://github.com/rxhanson/Rectangle/blob/cd87fbfb98c06f7a75661a04f1223bac95972cd4/README.md#window-movingresizing-appears-animatedsmooth-instead-of-quick-and-windows-dont-end-up-where-you-expect).
1. Open ["Accessibility Inspector"](https://developer.apple.com/library/archive/documentation/Accessibility/Conceptual/AccessibilityMacOSX/OSXAXTestingApps.html)
1. Inspect the window of an app know to have this issue (e.g. Google Chrome, Sublime Text, Outlook)
1. Select the application via the "Hierarchy" section
1. Note the value of "Enhanced User Interface", changing it to true if needed
1. Trigger a resize of the window using Rectangle
Using the above process, Rectangle v0.39 will not …

Fix incorrect window resizing by disabling AXEnhancedUserInterface

---

README.md

Installing via `brew cask ...` produces the following warning:
```
Warning: Calling brew cask install is deprecated! Use brew install [--cask] instead.
```
More info [here](https://brew.sh/2020/09/08/homebrew-2.5.0/). Not familiar enough with the `brew` ecosystem to know if versioning is a concern here, but this replacement works on `brew --version == 2.6.1`.

Update installation to reflect `brew cask` deprecation

---

Rectangle.xcodeproj/project.pbxproj
Rectangle/WindowCalculation/BottomHalfCalculation.swift
Rectangle/WindowCalculation/LeftRightHalfCalculation.swift
Rectangle/WindowCalculation/LowerLeftCalculation.swift
Rectangle/WindowCalculation/LowerRightCalculation.swift
Rectangle/WindowCalculation/MoveLeftRightCalculation.swift
Rectangle/WindowCalculation/MoveUpDownCalculation.swift
Rectangle/WindowCalculation/RepeatedExecutionsCalculation.swift
Rectangle/WindowCalculation/RepeatedExecutionsInThirdsCalculation.swift
Rectangle/WindowCalculation/TopHalfCalculation.swift
Rectangle/WindowCalculation/UpperLeftCalculation.swift
Rectangle/WindowCalculation/UpperRightCalculation.swift

I refactored this as part of #283, but figured it was probably too off-topic for the same PR, so I held off submitting it until that was merged. This extracts the logic for handling the 1/2 - 2/3 - 1/3 to a sub-protocol of `RepeatedExecutionsCalculation`, called `RepeatedExecutionsInThirdsCalculation`.
I’ve now realised that `RepeatedExecutionsCalculation` doesn’t have any members that aren’t `RepeatedExecutionsInThirdsCalculation`, but I imagine that may change in future so I’ve left it in. It may be worth replacing `RepeatedExecutionCalculation`’s named methods with an array of function at some point, if the number of steps in the cycle needs to vary.

Factor out logic of cycling 1/2 - 2/3 - 1/3

---

README.md

The option `Cycle displays` isn't present in the preferences window any longer since the UI label changed.  This PR updates the readme to reflect the new name.

Update halve-to-thirds setting label in README

---

Rectangle/zh-Hant-TW.lproj/Main.strings

- Fix the item "Ignore frontmost.app" translation from “忽略 frontmost.app” to “忽略「frontmost.app」”.
修正項目"Ignore frontmost.app" 之翻譯，自「忽略 frontmost.app」修正為「忽略「frontmost.app」」。

Fix Taiwan Traditional Chinese File

---

Rectangle/it.lproj/Main.strings

I translated the new lines in Rectangle 0.49, I would like to ask you about the "Todo mode" translation because Todo in italian it's not very self-explanatory, maybe something like "In Evidenza" would be better in the italian translation, which explain the idea of a pinned app on the right of the screen.

Updated italian translation

---

Rectangle.xcodeproj/project.pbxproj
Rectangle/WindowAction.swift
Rectangle/WindowCalculation/BottomCenterNinthCalculation.swift
Rectangle/WindowCalculation/BottomLeftNinthCalculation.swift
Rectangle/WindowCalculation/BottomRightNinthCalculation.swift
Rectangle/WindowCalculation/MiddleCenterNinthCalculation.swift
Rectangle/WindowCalculation/MiddleLeftNinthCalculation.swift
Rectangle/WindowCalculation/MiddleRightNinthCalculation.swift
Rectangle/WindowCalculation/NinthsRepeated.swift
Rectangle/WindowCalculation/TopCenterNinthCalculation.swift
Rectangle/WindowCalculation/TopLeftNinthCalculation.swift
Rectangle/WindowCalculation/TopRightNinthCalculation.swift
Rectangle/WindowCalculation/WindowCalculation.swift
TerminalCommands.md

Thank you for this project!
I personally love ninths, as 4k screens are pretty common in the mac ecosystem and it's handy to be able to stack things like terminals.  I saw in [this discussion](https://github.com/rxhanson/Rectangle/discussions/396) that you would be open to a PR for adding ninths to Rectangle so I thought I'd give it a whirl.
**What's added**
1. Support for "ninths" calculations, without a UX, meaning it is possible to configure hotkeys via terminal commands for folks who are interested in that sort of thing.
-- 
Note that an earlier version of this PR included UI / UX for setting shortcuts and accessing ninths via the menu.  This was removed as part of the PR review, though the UI still exists [in this commit](https://github.com/slifty/Rectangle/commit/2b22a084017896dfeb97 …

Add ninths

---

CONTRIBUTING.md
README.md
TerminalCommands.md

Replaces references to Hookshot with Rectangle Pro and removes the 'Available in v0.50' notices from TerminalCommands.md

Update readme files

---

Rectangle.xcodeproj/project.pbxproj
Rectangle/WindowAction.swift
Rectangle/WindowCalculation/BottomLeftThirdCalculation.swift
Rectangle/WindowCalculation/BottomRightThirdCalculation.swift
Rectangle/WindowCalculation/HorizontalThirdsRepeated.swift
Rectangle/WindowCalculation/TopLeftThirdCalculation.swift
Rectangle/WindowCalculation/TopRightThirdCalculation.swift
Rectangle/WindowCalculation/WindowCalculation.swift
TerminalCommands.md

This PR adds four new regions which can be configured via command line.
They are "horizontal" thirds (from the perspective of landscape; in portrait they are vertical).  They are still taking up 1/3 of the screen, just... horizontally!
Specifically the four new layouts are:
```
1   2   3   4
TL  TR  BL  BR
XXO OXX OOO OOO
OOO OOO XXO OXX
Top Left (TL)
Top Right (TR)
Bottom Left (BL)
Bottom Right (BR)
```
Similar to the ninghts PR (#702) this supports repeating commands to rotate through the four options.

Add horizontal thirds

---

Rectangle/TodoMode/TodoManager.swift

Rectangle Version 0.50 (55)
Fix for #713 
Application windows now consider the dock positition and will not be placed underneath the dock
1. todoWindow uses the adjustedVisibleFrame(which uses visibleFrame). When the dock is set to the right side, todoWindow will now placed next to it rather than under it
2. adjustedVisibleFrame is now used to calculate the positions for all non-todo application windows.
3. Changed the following in the shiftWindowOffSidebar function
a. Uses adjustedVisibleFrame instead of screenFrame. Helps when dock is placed on the left side
b. Handles an edge case where an application window is already placed at left edge or even further left. Origin X will be its current x in this case
c. The condition for checking if the application window is too wide. It now …

Bug Fix for #713

---

Rectangle/Defaults.swift
Rectangle/ScreenDetection.swift
TerminalCommands.md

Hi there 👋 
This PR adds another hidden preference to apply the screen gaps only to the main/primary screen.
I find it quite useful since I have uBar as dock replacement on the primary screen only. Without that the set gaps will be applied on non primary screens too which don't have any dock leaving some unused screen space.

Add option to apply gaps to the main screen only

---

Rectangle/ScreenDetection.swift

Hello again 😃 
It is about my [last PR](https://github.com/rxhanson/Rectangle/pull/798), you did some refactoring and inverted the logic by accident. 😬  Instead of applying the gaps to the main screen only it does it only for non main screens now. I fixed it with this PR.

fix: screenEdgeGapsOnMainScreenOnly logic inverted

---

Rectangle/Snapping/SnappingManager.swift

Adds snap areas for top center and bottom center sixths (in addition to the corner sixths added in #799) by first dragging to a corner, then along the top/bottom edge past the corner sixth snaps to the middle of the top/bottom edge.

Added support for center sixth snap areas

---

.github/workflows/build.yml
README.md

Building on the fine work by @Aaron-Rumpler in #812 - this bumps the actions to `@v3` major versions.
Also regenerated the `Build` button using GitHub's own "Create status badge" UI, which adds a URL to make button link to workflow run log page.

Bump GitHub action versions

---

Rectangle/ja.lproj/Main.strings

The wordings are adapted as much as possible to those of the official Apple website in Japan.

Add Japanese localization about state manager

---

Rectangle/ScreenDetection.swift
Rectangle/Utilities/StageUtil.swift

Stage Manager: only one window case

---

Rectangle/Snapping/SnappingManager.swift

When Stage Manager is enabled, it seems that new windows are moved away from the lateral edges of the screen, which is an issue for the footprint window. The proposed fix is to "show" the window before adjusting its frame.

Stage Manager: avoid footprint window being moved

---

Rectangle/AccessibilityElement.swift
Rectangle/PrefsWindow/SettingsViewController.swift
Rectangle/ScreenDetection.swift
Rectangle/Utilities/StageUtil.swift

Stage Manager: snap windows from recent apps

---

Rectangle/Base.lproj/Main.storyboard
Rectangle/Defaults.swift
Rectangle/PrefsWindow/SnapAreaViewController.swift
Rectangle/Snapping/EventMonitor.swift
Rectangle/Snapping/SnappingManager.swift
Rectangle/Utilities/NotificationExtension.swift

Related to #902. Maybe change the sensitivity which is the `-25` value?

Disable fast dragging to Mission Control

---

Rectangle.xcodeproj/project.pbxproj
Rectangle/AccessibilityElement.swift
Rectangle/AppDelegate.swift
Rectangle/ApplicationToggle.swift
Rectangle/Base.lproj/Main.storyboard
Rectangle/MultiWindow/MultiWindowManager.swift
Rectangle/MultiWindow/ReverseAllManager.swift
Rectangle/PrefsWindow/SettingsViewController.swift
Rectangle/ScreenDetection.swift
Rectangle/ShortcutManager.swift
Rectangle/Snapping/SnappingManager.swift
Rectangle/TodoMode/TodoManager.swift
Rectangle/Utilities/AXExtension.swift
Rectangle/Utilities/CFExtension.swift
Rectangle/Utilities/CGExtension.swift
Rectangle/Utilities/SequenceExtension.swift
Rectangle/Utilities/StageUtil.swift
Rectangle/Utilities/WindowUtil.swift
Rectangle/WindowCalculation/WindowCalculation.swift
Rectangle/WindowManager.swift
Rectangle/WindowMover/BestEffortWindowMover.swift
Rectangle/WindowMover/CenteringFixedSizedWindowMover.swift
Rectangle/WindowMover/QuantizedWindowMover.swift
Rectangle/WindowMover/StandardWindowMover.swift

- I can't reproduce #989. It looks like this is due to an infinite loop that occurs when the window ID cannot be determined directly. This ID is now cached.
- There is now a detection of the windows belonging to the strip which allows to disable their snapping when needed as suggested in #854.
- The maximum width of the recent apps area has been increased for #981.

Stage Manager

---

Rectangle/Defaults.swift
Rectangle/Snapping/CompoundSnapArea/CompoundSnapArea.swift
Rectangle/Snapping/CompoundSnapArea/FourthsCompoundCalculation.swift
Rectangle/Snapping/CompoundSnapArea/HalvesCompoundCalculation.swift
Rectangle/Snapping/CompoundSnapArea/SixthsCompoundCalculation.swift
Rectangle/Snapping/CompoundSnapArea/ThirdsCompoundCalculation.swift
Rectangle/Snapping/SnappingManager.swift
TerminalCommands.md

Add optional animations to the footprint window.

Add footprintAnimationDurationMultiplier default

---

Rectangle/AccessibilityElement.swift
Rectangle/ScreenDetection.swift
Rectangle/Snapping/SnappingManager.swift
Rectangle/Utilities/AXExtension.swift
Rectangle/Utilities/StageUtil.swift
Rectangle/Utilities/WindowUtil.swift

It seems to be unnecessary for the main window since at least the release of macOS 13.

Stage Manager: clean up workaround

---

Rectangle/Defaults.swift
Rectangle/ScreenDetection.swift
TerminalCommands.md

Hi!
Love this app, thanks for all your work on this. 
Since macOS Ventura, I️ am a huge fan of Stage Manager, but I️ switch from my desktop monitor setup to my laptop quite often. With the screens being vastly different sizes, the absolute pixel width value that Rectangle currently allows for is too much when using my laptop dimensions. Like, setting it to the perfect width when on my monitor resulted in the stage area being too large on my laptop. 
This PR adds an option to set a percentage of the screen width rather than a simple absolute value. If the percentage is set (defaults to 0), it is used over any set "stageSize" value. I️ did not add UI for this, as it is quite niche, just a reference from the config file if set. 
Locally my build works fine, but I️ was _not_ able to fully …

Allow configuration option for stageSize to be treated as a percentage if less than 1

---

Rectangle/PrefsWindow/SettingsViewController.swift
Rectangle/RectangleStatusItem.swift
Rectangle/Utilities/NotificationExtension.swift

AppKit settings took priority.

Sync status item removal by dragging with settings

---

README.md

Adds a link to the keyboard shortcuts guide to make it easier to see what key each shortcut maps to.

Add link to Mac keyboard shortcut guide

---

Rectangle.xcodeproj/project.pbxproj
Rectangle/AppDelegate.swift
Rectangle/Base.lproj/Main.storyboard
Rectangle/Defaults.swift
Rectangle/MultiWindow/MultiWindowManager.swift
Rectangle/MultiWindow/ReverseAllManager.swift
Rectangle/PrefsWindow/Config.swift
Rectangle/PrefsWindow/SettingsViewController.swift
Rectangle/ScreenDetection.swift
Rectangle/ShortcutManager.swift
Rectangle/Snapping/SnappingManager.swift
Rectangle/TodoMode/TodoManager.swift
Rectangle/WindowAction.swift
Rectangle/WindowCalculation/CenterCalculation.swift
Rectangle/WindowCalculation/ChangeSizeCalculation.swift
Rectangle/WindowCalculation/LeftRightHalfCalculation.swift
Rectangle/WindowCalculation/LeftTodoCalculation.swift
Rectangle/WindowCalculation/MoveLeftRightCalculation.swift
Rectangle/WindowCalculation/NextPrevDisplayCalculation.swift
Rectangle/WindowCalculation/RightTodoCalculation.swift
Rectangle/WindowCalculation/WindowCalculation.swift
Rectangle/WindowManager.swift

- Correction of the target of the toggling selector when the settings have the first responder.
- Disable reflow when mode is disabled.
- Automatic reflow after changing settings.
- Ignore sidebar area for actions on the sidebar window.
- The sidebar window can be resnapped to the sidebar area.
- Add a shortcut to toggle mode.
- Save shortcuts to the config.
- Add a setting for the sidebar side.

Todo Mode improvements

---

Rectangle/AppDelegate.swift
Rectangle/ScreenDetection.swift
Rectangle/TodoMode/TodoManager.swift

- Be able to switch the Todo window explicitly rather than having to close the previous one.
- Ignore the Todo window if it doesn't exist in the calculation of the frames of the other windows.

Todo Mode refinements

---

Rectangle/ja.lproj/Main.strings

- "Settings" should be translated to just "設定" instead of "環境設定"
- L405 and L621
- Fix mistranslation
- L603: `左中央` to `中央上`
- L612: `左中央` to `中央下`
- Add translations for new strings
- Follow the Apple's translation against "window": use "ウインドウ" instead of "ウィンドウ"

Update Japanese translation

---

Rectangle/MultiWindow/MultiWindowManager.swift
Rectangle/WindowAction.swift
TerminalCommands.md

Changes:
- enum `WindowAction`: add `case cascadeActiveApp` and update functions that handle the cases
- `class MultiWindowManager`: add `cascadeActiveAppWindowsOnScreen()` and a call from `execute()`
- `TerminalCommands.md`: add section `## Add additional tiling and cascading commands`
@rxhanson @dirondin 
Please review the proposed changes and test them.
I tested the debug build on my Intel Mac (2017), and it works to my satisfaction.
Let me know if I missed anything. Kudos to both of you for the clean and understandable code, easy to extend.
@rudifa

add action cascadeActiveApp; add cascadeActiveAppWindowsOnScreen

---

README.md

Going through the docs, I noticed some outdated information about Cocoapods being used.

Remove information about Cocoapods and replace it with SPM

---

Rectangle.xcodeproj/project.pbxproj
Rectangle/nb.lproj/Main.strings
Rectangle/nn.lproj/Main.strings
RectangleLauncher/nb.lproj/Main.strings
RectangleLauncher/nn.lproj/Main.strings

Didn't manage to build, so haven't been able to test how well the translations fit the available space in the UI. Would it be possible to get a prerelease build that I could test?

Localisation to Norwegian (Nynorsk)/NN, added untranslated files for a possible Norwegian (bokmål)/NB translation

---

Rectangle/AccessibilityElement.swift
Rectangle/Utilities/CFExtension.swift
Rectangle/Utilities/WindowUtil.swift

Tries to fix https://github.com/rxhanson/RectanglePro-Community/issues/353

Filter level when getting window by location

---

Rectangle.xcodeproj/project.pbxproj
Rectangle/WindowAction.swift
Rectangle/WindowCalculation/CenterProminentlyCalculation.swift
Rectangle/WindowCalculation/WindowCalculation.swift
TerminalCommands.md

Changes:
- Add a `CenterProminently` command that centers the window horizontally, but moves the window up vertically slightly from the center to give visual importance.
- Add documentation to `TerminalCommands.md`
This follows from the discussion here https://github.com/rxhanson/Rectangle/discussions/1285. Thank you for making the code easy to follow!

Add centerProminently command

---

Rectangle/AccessibilityElement.swift
Rectangle/TitleBarManager.swift

Fixes #1293. Search in children rather than just using the API.

Fix title bar element detection

---

Rectangle/Defaults.swift
Rectangle/ScreenDetection.swift
TerminalCommands.md

The top gap is calculated from the notch. This means windows overlap custom menubars when having external displays, as the gap is either too small on the external or huge on the built in display. Tried to explain this coherently, hope it makes sense

Add separate gap for notched display

---

README.md

Adds some pointers to the documentation to help those with Homebrew uninstallation where `--zap` is required otherwise, they may see issues with configuration persisting when upgrading from older versions.
Closes #1246

docs: update README to mention `--zap` for Homebrew uninstall

---

Rectangle.xcodeproj/project.pbxproj
Rectangle/mul.lproj/Main.xcstrings

Edited using XCode 15.0.1.
* Add translations for British English
* Use British spelling for some words
* Use 'Quarter' instead of 'Fourths' in the menu

Add British English as a Translation

---

Rectangle.xcodeproj/project.pbxproj
Rectangle/AppDelegate.swift
Rectangle/Defaults.swift
Rectangle/Utilities/MacTilingDefaults.swift
Rectangle/Utilities/StringExtension.swift
Rectangle/mul.lproj/Main.xcstrings

Prompt the user to either disable the built-in macOS tiling in Sequoia or disable Rectangle's tiling (I prefer Rectangle's tiling :)

Inform the user when macOS 15 tiling is enabled

---

Rectangle/mul.lproj/Main.xcstrings

Added translations for new or needs-review strings.
Needs Review item:
For "Dismiss" there's multiple translation and I'm not entirely certain on the context so I kept it as Needs Review.
Currently I added it as "忽略" which means either disregard or ignore(as in ignoring the warning/alert/notification). 
But if it should mean :
1. cancel - as in cancelling an action, "取消“ should be used;
2. close- as in closing the dialog/notification popup, "关闭" would be more appropriate.

Update simplified chinese translation

---

Rectangle/AppDelegate.swift

I forgot to add a check for this in my last pull request.

Check if window snapping is enabled prior to prompting user to disable it

---

Rectangle/MultiWindow/MultiWindowManager.swift

This PR proposes refinements to the command `cascadeActiveApp` (published in `rectangle v0.69` from PR #1146 and #1163)
- before: the cascade goes to the top left quadrant
- now: the cascade goes to the quadrant in which the center of the active window is found, so that the user can have up to 4 different apps cascaded
- before: the size of the active (first) window is enforced onto the other windows in the cascade
- now: same, but the size width and height are constrained so that all cascaded windows remain within the screen

Add CascadeActiveAppWindows refinements

---

Rectangle/mul.lproj/Main.xcstrings

The British English spelling of "center" was missed from the translation added in  #1411, this PR should rectify that.

Add remaining few British English translations of "center"

---

Rectangle.xcodeproj/project.pbxproj
Rectangle/Base.lproj/Main.storyboard
Rectangle/CycleBetweenDivisions.swift
Rectangle/CycleSize.swift
Rectangle/Defaults.swift
Rectangle/PrefsWindow/SettingsViewController.swift
Rectangle/WindowCalculation/RepeatedExecutionsCalculation.swift
Rectangle/WindowCalculation/RepeatedExecutionsInThirdsCalculation.swift
Rectangle/mul.lproj/Main.xcstrings

As people use a variety of screen sizes, it is desirable to cycle between different window sizes instead of / in addition to ½, ⅔ and ⅓. 
Example use cases:
- Working on a laptop that you occasionally connect to a larger external display, you might use the 1/3rd fraction on the laptop display and 1/4th fraction on the external display.
- If you never use one of the sizes, say 1/3rd fraction, it should be possible to disable it
- Selecting On repeated commands: “cycle between sizes for half actions” shows checkboxes with the possible sizes to enable and disable.
- Changed text of menu item from “cycle between ½, ⅔ and ⅓ for half actions” to “cycle between sizes for half actions”.
- Two new user defaults: `cycleBetweenDivisions` and `cycleBetweenDivisionsIsChanged`.
- Animate toggling …

Repeated commands: Select which sizes to cycle between on repeated half actions

---

Rectangle/Utilities/AXExtension.swift

Due to a change implemented in Swift 5.9, [Constrain implicit raw pointer conversion to bitwise-copyable values](https://github.com/atrick/swift-evolution/blob/diagnose-implicit-raw-bitwise/proposals/nnnn-implicit-raw-bitwise-conversion.md), a conversion to a raw pointer produces the warning: `Forming an 'UnsafeRawPointer' to a variable of type 'T'; this is likely incorrect because 'T' may contain an object reference.`
Since the affected function is only used with `CGPoint` and `CGSize`, the current implementation—that raises the warning—should be harmless.
The warning has been silenced by wrapping the code in `withUnsafePointer(to:) {}`.
---
Another possible solution could be to constrain `T` to the [`BitwiseCopyable`](https://github.com/swiftlang/swift-evolution/blob/main/proposals/0426- …

Silence warning in AXExtension

---

Rectangle/AppDelegate.swift
Rectangle/PrefsWindow/SnapAreaViewController.swift
Rectangle/ScreenDetection.swift
Rectangle/Snapping/SnapAreaModel.swift
Rectangle/Utilities/MacTilingDefaults.swift
Rectangle/mul.lproj/Main.xcstrings

In the macOS 15.1 beta, there's an additional setting for the top snap area that needs to be checked by Rectangle.

Handle additional tiling setting in macOS 15.1

---

Rectangle/Utilities/MacTilingDefaults.swift

Without this change, the top tiling conflict warning could be displayed to users of macOS < 15.1.

Restrict top tiling check to macOS 15.1
