- Rectangle/it.lproj/Main.strings
I've improved the Italian translation, let me know if there are some problems.
Thank you
> Pull request for Italian l18n

- Rectangle/ko.lproj/Main.strings
Replaced Google-translated strings with more natural wordings.
I don't think there are proper translations for "two thirds," "Last Third," etc., so I replaced them with 1/3 or 2/3 with a translation for "left" and "right".
> Updated Korean Main.strings

- README.md
> Small update to readme for markdown bash syntax

- README.md
> Add a screenshot to quickly show what the app can do

- Rectangle/ru.lproj/Main.strings
* Translated what was translated badly
* Re-phrased the phrases
* Used established terms
Also this file looks like it was copied from some text editor, but I still translated everything to make sure I didn't miss something important.
> Made Russian locale more Russian

- README.md
I felt it was an important feature that should be easily discoverable.
Based on https://github.com/rxhanson/Rectangle/issues/47
> How to ignore an app

- Rectangle/zh-Hans.lproj/Main.strings
Use a more precise verb words to express `Move`.
Use `left` `right` replace `first` `last` to reflect Chinese convention.
> Correct wrong zh-Hans translations manually 2

- Rectangle/zh-Hant.lproj/Main.strings
- Replaced machine translations by making references to the macOS wordings
- Some unused menu items had not been translated
> Localizations for zh-Hant (Traditional Chinese)

- Rectangle/zh-Hans.lproj/Main.strings
Use a more precise verb words to express `Move`.
Fix wrong translation.
> Correct wrong zh-Hans translations manually 3

- Rectangle/Info.plist
Great project! I love Spectacle, but I had to install Rectangle on a new Mac. Glad that it exists!
I noticed that the copyright date was set to 2019, so I went ahead and bumped it for you. Happy new year! 🎉
> Update copyright date

- Rectangle/ja.lproj/Main.strings
As you can see
"First Third" → "最初の1/3" not "最初の3番目"
"Center Third" → "中央の1/3"
"Last Third" → "最後の1/3"
> "最初の1/3" is more appropriate translation for "First Third".

- README.md
- Rectangle/Defaults.swift
- Rectangle/WindowCalculation/ChangeSizeCalculation.swift
As per #124 
Unsure if `minimumWindowWidth` and `minimumWindowHeight` naming makes sense, let me know if you'd like me to change them.
Tested when running in Debug mode btw.
> Added defaults variables to control the minimum width/height

- Rectangle/zh-Hans.lproj/Main.strings
correct incorrect Simplified Chinese localizations to make it more Chinese
> Simplified Chinese localizations update

- Rectangle/pl.lproj/Main.strings
I updated Polish translations so they sound more natural
> Update Polish translation

- Rectangle/zh-Hant-TW.lproj/Main.strings
Optimize Traditional Chinese (Taiwan) translate
修正正體中文 (臺灣) 的翻譯用字
> Optimize Traditional Chinese (Taiwan) translate

- Rectangle/es.lproj/Main.strings
Updating some of the Spanish translations.
> Update spanish translations

- Rectangle/it.lproj/Main.strings
Add Italian translation to untranslated strings (welcome window) and fix some singular/plural accordance in the use of word _abbreviazione_ (_abbreviazion**e**_ = one, _abbreviazion**i**_ = many)
> Improve IT translation

- Rectangle/ko.lproj/Main.strings
1. Updated some translations to make it more united
1. Fixed typos
1. Translated texts for welcome page
> Update KO translation

- Rectangle/ko.lproj/Main.strings
Updated it a few hours ago, but I found some issues again and had to make PR again.
> Update KO localization again a little bit

- Rectangle/ja.lproj/Main.strings
Hey, Ryan!
I just installed this app last night, and it has already made a big difference in my productivity. I didn't realize how much time I've lost without it!
I hope this Japanese translation update helps. Cheers! 😁
> Updated Japanese translation

- Rectangle/ja.lproj/Main.strings
Change suggested by @ryonakano in #219.
We are full steam ahead! 🚂
> Corrected Japanese translation

- Rectangle/pt-PT.lproj/Main.strings
- RectangleLauncher/pt-PT.lproj/Main.strings
I might take another look at this, but I fixed several glaring machine translation errors and localized RectangleLauncher.
> First pt-PT human localization.

- README.md
> Update readme for screen edge gaps settings

- Rectangle/pl.lproj/Main.strings
Update for Polish localization after introducing new strings in v0.34.
This year I decided to take part in Hacktoberfest. If you find it useful, I would be happy to get this PR labelled with "hacktoberfest-accepted", if possible :)
> Update Polish localization

- Rectangle/es.lproj/Main.strings
New 0.3.4 translations for es-ES language.
> Spanish translation

- Rectangle/zh-Hans.lproj/Main.strings
> Update zh-Hans Main.strings

- Rectangle/de.lproj/Main.strings
Hello, I have made a few small grammatical adjustments to the German translation.
> Small grammatical adjustments to the German translation

- Rectangle/fr.lproj/Main.strings
Full proofreading of French localization: corrected existing vocabulary according to Apple guidelines and added all new strings not translated.
> French localization updated for v0.35

- Rectangle/fr.lproj/Main.strings
Small more typos corrected after previous proofread.
> Update French localization for v0.35

- Rectangle/pt-BR.lproj/Main.strings
Updating the existing translations and adding the new ones from the last update!
I've been meaning to do this for some time and got the extra motivation due to the current Hacktoberfest. Would appreciate if you could label the PR `hacktoberfest-accepted` if you find that it contributes to the project! :)
> Update pt-BR translations

- Rectangle/ja.lproj/Main.strings
- Fix wrong translations
- Follow the translations used in macOS
- Complete missing translations
> Update Japanese translation

- Rectangle/ja.lproj/Main.strings
please see https://github.com/rxhanson/Rectangle/issues/256
> Close the double quotation for ja.lproj/Main.strings #256

- Rectangle/nl.lproj/Main.strings
Some improvements to fractions and positions/positioning in Dutch.
> Improved Dutch translations for fractions and positioning

- Rectangle/es-419.lproj/Main.strings
> Semantic issue on lines 153, 294, 612

- Rectangle/zh-Hant-TW.lproj/Main.strings
Optimized Chinese Taiwan Localization
> Optimized Chinese Taiwan Localization

- Rectangle/WindowManager.swift
At the moment, `lastRectangleAction` is only updated when the operation caused the window to move. This means that, if an operation wouldn’t cause a move when it is first pressed, but instead only after a second press, then it actually has no effect on any subsequent press.
This PR fixes this, by updating `lastRectangleAction` explicitly when a move does not cause any effect.
Fixes #293
> Record no-op operations, to fix repeated actions

- Rectangle/zh-Hant-HK.lproj/Main.strings
- Rectangle/zh-Hant-TW.lproj/Main.strings
- Rectangle/zh-Hant.lproj/Main.strings
Hi, I have added a few missing translations and fixed some bad translations for `zh-Hant`, `zh-Hant-HK` and `zh-Hant-TW`.
Please take a look of them and merge it if everything is fine.
> add missing zh-hant translations

- Rectangle/ko.lproj/Main.strings
Hi, thanks for making a good app!
> Add Korean translation

- README.md
Hello 👋
First of all, thank you for giving continuity to such an essential tool.
I'm part of the group moving from Spectacle and one of the features I missed the most was **third cycling**. I understand how granular third shortcuts can be helpful, however, it can also become a burden having to memorize multiple shortcuts.
Luckily I found #13 with a solution on how to emulate third cycling. Since this isn't straightforward, I would like to suggest clarifying that in the differences for future pre-Spectacle adopters like me.
> Update README.md with third cycling

- Rectangle/zh-Hans.lproj/Main.strings
- Rectangle/zh-Hant-HK.lproj/Main.strings
- Rectangle/zh-Hant-TW.lproj/Main.strings
- Rectangle/zh-Hant.lproj/Main.strings
All Chinese translations (zh-Hans, zh-Hant, zh-TW, zh-HK) are corrected and polished.
> Correcting Chinese translation

- README.md
Updated README.md with a line on how to use the JSON import/export functionality.
> Add documentation regarding import/export functionality

- Rectangle.xcodeproj/project.pbxproj
- Rectangle/AppDelegate.swift
- Rectangle/Defaults.swift
- Rectangle/WindowAction.swift
- Rectangle/WindowCalculation/SpecifiedCalculation.swift
- Rectangle/WindowCalculation/WindowCalculation.swift
Depends on #209, I made changes to my code.
For now, to add the shortcut to the `specified` action, you should write some defaults like:
```sh
defaults write com.knollsoft.Rectangle specified -dict-add keyCode -float 8 modifierFlags -float 1966080
```
because I didn't change any UI and didn't add the menu to add shortcuts
keyCode: 8 
modifierFlags: 1966080
it's `CMD + OPTION + CTRL + SHIFT + C`
I have no idea how to make it more user-friendly without changes in UI. :)
> Add `specified` WindowAction

- Rectangle/it.lproj/Main.strings
Hello, I would like to help you with the translation of Rectangle! I translated the missing lines, and also changed "abbreviazioni -> scorciatoie", shortcuts is closer to italian "scorciatoie", "abbreviazioni" is when you write for example Mr. instead of Mister, it's something else. I turned "check for updates automatically" in the shorter "aggiornamenti automatici" because the translated line in the app UI was overlapping with the "check for updates" button, it was too long. I hope you may find this changes useful, thank you for your great work with this app.
> Update Italian locale

- Rectangle/ja.lproj/Main.strings
Hi
> Rectangle v0.48
> Added the ability to move the cursor along with the window when moving across displays, along with a toggle in the preferences window.
translated it into Japanese.
> Update Japanese locale

- Rectangle/it.lproj/Main.strings
as we said, I updated the lines to be more consistent with Apple's localization. I changed some menu bar lines too to match the translation from system apps.
> Update Italian locale v2

- Rectangle/it.lproj/Main.strings
I tested my updated main.strings in my Rectangle installation and I find out small errors so I fixed them. Everything else looks fine, from the menu bar to app preferences.
> Italian locale minor fixes

- Rectangle/pl.lproj/Main.strings
Updated "setting for moving cursor with window across displays" translation.
> Update Polish locale

- Rectangle/ko.lproj/Main.strings
- Replaced some words in order to match with previously used words
- window: 윈도우 ➡️ 창
- display: 화면 ➡️ 디스플레이
- Fill empty strings
- Add translations
(더 나은 번역이 있으면 제안 부탁드립니다)
> Update Korean translation

- README.md
made with https://badgen.net/homebrew
> Add brew monthly download badge

- Rectangle/de.lproj/Main.strings
I've fixed some minor issues with the German translation (typo, wording and consistency) and added translations for the Todo Mode.
> Update German localization

- Rectangle/zh-Hans.lproj/Main.strings
1. Update Todo Mode related transitions.
2. Adjust some translations for better understanding when screen in portrait mode.
> Update simplified Chinese translation.

- Rectangle/fr.lproj/Main.strings
Hi, thanks for the app, it's great! Here's my modest contribution to the project: I completed the French translation.
> completed French translation

- Rectangle/ko.lproj/Main.strings
> Update korean translation of Todo mode

- CONTRIBUTING.md
- README.md
- Rectangle/Defaults.swift
- Rectangle/WindowAction.swift
- TerminalCommands.md
Added `applyGapsToMaximize` and`applyGapsToMaximizeHeight` preferences (on by default) which specify whether gaps are applied to 'Maximize' and 'Maximize Height' actions.
> Added option to not apply gaps for maximize

- Rectangle/de.lproj/Main.strings
Hi! 👋  I have fixed two little typos in the german translation
> Fix typos in German localization

- Rectangle/ru.lproj/Main.strings
Translate Todo section to Russian language and minor fixes with translation "Shortcut" word.
Also I can make translation to Belarusian language 🤍❤️🤍 (🇧🇾)
> Update russian language translation

- Rectangle/pt-BR.lproj/Main.strings
- RectangleLauncher/pt-BR.lproj/Main.strings
Hi! 👋 Love your work! I've just added the finishing touches to the pt-BR localization. Have a great day!
> Added pt-BR localization to Rectangle and RectangleLauncher

- Rectangle/de.lproj/Main.strings
The German descriptions have been adapted to the exact wording of the translations of system apps in macOS to ensure better consistency.
Also, prompts have been adapted to the "Du" form of address commonly used in macOS.
> Some adjustments to the German translation

- Rectangle.xcodeproj/project.pbxproj
- Rectangle/Base.lproj/Main.storyboard
- Rectangle/Defaults.swift
- Rectangle/PrefsWindow/SettingsViewController.swift
- Rectangle/ScreenDetection.swift
- Rectangle/Utilities/StageUtil.swift
As the issue described in #829 seems to have been solved, I propose a basic support of Stage Manager, that is the configuration of the size of the area reserved for recent apps.
> Basic Stage Manager support

- Rectangle/ca.lproj/Main.strings
Congratulations on the app! I'd like to contribute with the catalan translation.
> Add Catalan translation

- RectangleLauncher/de.lproj/Main.strings
Not sure what Frontend and therefore context this is, so I updated it to the best of my abilities. (I use Rectangle on Mac and never saw a Launcher)
> Updated German Strings

- Rectangle/cs.lproj/Main.strings
- Rectangle/sk.lproj/Main.strings
Fixed some typos and added missing localized strings for Czech & Slovak languages
> updated cz & sk translations

- Rectangle/ScreenDetection.swift
> Stage Manager: Dock on the left case

- Rectangle/ru.lproj/Main.strings
Hi,
Updated the translation of the word `sixth`. New functionality has been translated.
> Update ru localization.

- Rectangle/zh-Hant-TW.lproj/Main.strings
Update and improve Traditional Chinese (Taiwan) translation.
> Update zh-Hant-TW localization

- Rectangle/de.lproj/Main.strings
Updated translation for disabeling fast dragging to Mission control
> Updated translation for disabeling fast dragging to Mission control

- Rectangle/zh-Hans.lproj/Main.strings
1. Optimized shortcuts description
2. Localized 'Disable fast dragging to Mission Control'
> Optimized localization zh-Hans.

- Rectangle.xcodeproj/project.pbxproj
- Rectangle/AccessibilityElement.swift
- Rectangle/ShortcutManager.swift
- Rectangle/Snapping/EventMonitor.swift
- Rectangle/Snapping/SnappingManager.swift
- Rectangle/TodoMode/TodoManager.swift
- Rectangle/Utilities/StageUtil.swift
- Rectangle/Utilities/WindowUtil.swift
- Rectangle/WindowAction.swift
- Rectangle/WindowCalculation/WindowCalculation.swift
- Rectangle/WindowHistory.swift
- Rectangle/WindowManager.swift
Mainly optimizations around `CGWindowListCopyWindowInfo`.
> Some refactoring

- README.md
- Rectangle/AppDelegate.swift
- Rectangle/Info.plist
- Rectangle/WindowAction.swift
- Rectangle/WindowManager.swift
> Execute action by URL

- Rectangle/zh-Hans.lproj/Main.strings
> Updated ZH-HANS localization.

- Rectangle.xcodeproj/project.pbxproj
- Rectangle/Snapping/SnappingManager.swift
- Rectangle/Utilities/DispatchTimeExtension.swift
- Rectangle/Utilities/WindowUtil.swift
> Improve "Disable fast dragging to Mission Control"

- Rectangle.xcodeproj/project.pbxproj
- Rectangle/Snapping/SnappingManager.swift
- Rectangle/Utilities/TimeoutCache.swift
- Rectangle/Utilities/WindowUtil.swift
Avoid that some elements remain indefinitely in memory.
> Purge cache in WindowUtil

- TerminalCommands.md
Updated a tip for Rectangle Pro Terminal Commands.
> Updated description of  Rectangle Pro.

- Rectangle/zh-Hant-TW.lproj/Main.strings
Update Chinese (Taiwan) translation for macOS Ventura.
- Go to System Settings → Privacy & Security → Accessibility
- Open System Settings
> Update zh-Hant-TW localization for Ventura

- Rectangle.xcodeproj/project.pbxproj
- Rectangle/Snapping/EventMonitor.swift
- Rectangle/Utilities/RunLoopThread.swift
This should limit the hangs and timeouts that result in #950.
> Run ActiveEventMonitor tap in its own thread

- Rectangle/ca-ES.lproj/Main.strings
Really small change, but it was bothering me that the other quarters were using a different approach to the string.
> Small change to normalise the top-right string with the other quarts

- Rectangle/Snapping/FootprintWindow.swift
Fixes an issue described in #1008.
> Fix footprint animation

- Rectangle/zh-Hans.lproj/Main.strings
- Added new translation
"吸附动画" for `Animate footprint`
> Updated Simplified Chinese translation

- Rectangle/ja.lproj/Main.strings
I've corrected some translations and added new ones.
> Correct Japanese localization

- Rectangle/es.lproj/Main.strings
Fixed "cycle" word traduction and added the missing translation strings.
> Add missing location translations for spanish.

- Rectangle.xcodeproj/project.pbxproj
- Rectangle/Defaults.swift
- Rectangle/ScreenDetection.swift
- Rectangle/Utilities/CGExtension.swift
- Rectangle/WindowCalculation/CenterCalculation.swift
- Rectangle/WindowCalculation/CenterHalfCalculation.swift
- Rectangle/WindowCalculation/OrientationAware.swift
- Rectangle/WindowCalculation/WindowCalculation.swift
- Rectangle/WindowManager.swift
Also improved some parts of the code alongside this change
> Center action ignores stage by default

- Rectangle/ko.lproj/Main.strings
Updated mistranslated/untranslated strings. It resolves #1054.
> Update korean translations (#1054)

- Rectangle/uk.lproj/Main.strings
Ref: https://github.com/rxhanson/Rectangle/discussions/1094
> feat: 🌐 Add 🇺🇦 Ukrainian translation

- Rectangle.xcodeproj/project.pbxproj
- Rectangle/AccessibilityElement.swift
- Rectangle/AppDelegate.swift
- Rectangle/Base.lproj/Main.storyboard
- Rectangle/Defaults.swift
- Rectangle/PrefsWindow/SettingsViewController.swift
- Rectangle/TitleBarManager.swift
- Rectangle/Utilities/EventMonitor.swift
- Rectangle/Utilities/NotificationExtension.swift
- Rectangle/WindowAction.swift
- Rectangle/WindowManager.swift
- TerminalCommands.md
Implements #1097. The detection of the title bar is a bit worse than the one of the system.
> Add double-click title bar

- Rectangle/AccessibilityElement.swift
- Rectangle/Snapping/FootprintWindow.swift
- Rectangle/Snapping/SnappingManager.swift
> Stage Manager: footprint window workaround

- Rectangle/zh-Hans.lproj/Main.strings
- Add new translations
- Adjust spacing (according to conventions, there should be a space between English letters and Chinese characters)
> Update Simplified Chinese localization

- Rectangle/es.lproj/Main.strings
Update spanish localizations for the new placeholders added in this commits: 
0003b52 49617c1 00a9f52
> Update spanish localizations for the new placeholders

- Rectangle/AccessibilityElement.swift
Fixes #1108. Search in children rather than using the specific attribute.
> Fix title bar close button detection

- TerminalCommands.md
> Fix doc to disable doubleClickTitleBarRestore

- Rectangle/PrefsWindow/Config.swift
Fixes [this](https://github.com/rxhanson/Rectangle/issues/566#issuecomment-1492919023).
> Fix export with disabled Todo shortcuts

- Rectangle/fr.lproj/Main.strings
Add french translations the 3 new strings.
Thank you for the work done on the project :)
> Update French translation

- Rectangle.xcodeproj/project.pbxproj
- Rectangle/vi.lproj/Main.strings
- RectangleLauncher/vi.lproj/Main.strings
> Add Vietnamese translation

- Rectangle.xcodeproj/project.pbxproj
- Rectangle/Base.lproj/Main.storyboard
- Rectangle/lt.lproj/Main.strings
- RectangleLauncher/lt.lproj/Main.strings
Added Lithuanian localisation.
> Added Lithuanian language translation

- TerminalCommands.md
@rxhanson better late than never
> fix alonne -> alone

- Rectangle/es.lproj/Main.strings
Update spanish localizations for the updated features added in bc3a226ab488a493a6678a3791b26015a3f561b4
> Update Spanish localizations

- Rectangle/de.lproj/Main.strings
- RectangleLauncher/de.lproj/Main.strings
- Updated german translation
Thanks for your work on Rectangle!
> German translation updated

- Rectangle/Snapping/FootprintWindow.swift
- Rectangle/Utilities/StageUtil.swift
> Stage Manager: fix multi-space

- Rectangle/mul.lproj/Main.xcstrings
- Add the latest strings through String Catalog
> Update SC localization

- Rectangle/mul.lproj/Main.xcstrings
Replaced some translations with more accurate ones🎩
> Correct Russian translation

- README.md
- Rectangle/AppDelegate.swift
In case the sender has activated Rectangle.
> Try to deactivate Rectangle when executing action by URL

- Rectangle/Base.lproj/Main.storyboard
- Rectangle/Defaults.swift
- Rectangle/PrefsWindow/SnapAreaViewController.swift
- Rectangle/Snapping/SnappingManager.swift
- Rectangle/mul.lproj/Main.xcstrings
This is my first contribution to this project, so if there are any issues or suggestions, please don't hesitate to let me know.
In this pull request, I've implemented support for haptic feedback when moving a window onto a snap area. A simple setting that now I cannot live without :)
> Add Haptic Feedback Support for Window Snapping

- Rectangle/AccessibilityElement.swift
- Rectangle/TitleBarManager.swift
> Add title bar tab group support

- Rectangle/AppDelegate.swift
> Fix disabling Rectangle tiling when user selects it as prompted

- Rectangle/Base.lproj/Main.storyboard
- Rectangle/mul.lproj/Main.xcstrings
> Turn Slovak localization submission into a PR

- Rectangle/mul.lproj/Main.xcstrings
Improvements to the German localization. Some missing translations in connection with the todo mode have been translated.
> Update Main.xcstrings (DE localization)

- TerminalCommands.md
I really enjoyed using this project, nice work! Caught a couple of typos though 😛
> Update TerminalCommands.md, fix typos

- Rectangle/mul.lproj/Main.xcstrings
The translation has been slightly improved and missing translations have been added.
> Updated German translation in Main.xcstrings

- README.md
Shamelessly copied your explanation from https://github.com/rxhanson/Rectangle/issues/47 and added an additional clarification, after I was wondering what "ignore app" means and how I would un-ignore it.
> Update README.md - Clarified Ignoring an App

- Rectangle/MultiWindow/MultiWindowManager.swift
> chore: fix typo
